kind: pipeline
type: docker
name: FoxPipeline

steps:
- name: Project FoxKernel
  image: starlight2834/ci_docker:latest
  environment:
    BOT_API_KEY:
      from_secret: BOT_API
    ID:
      from_secret: ID
  commands:
  - "curl https://raw.githubusercontent.com/Fox-kernel/myscripts/master/mido_Weekly.sh | bash"
